Déclencher le moissonnage depuis l'API
BaseAdresseNationale/moissonneur-bal pull request #26
Opened 2022-10-12 13:44 UTC by cedric-famibelle-pronzola

- Création de `lib/routes`
- Ajout de la variable d'environnement `ADMIN_TOKEN`
- Création de la route `POST /admin/start-harvest`
- Création de `lib/util/harvest`
- Ajout de la dépendance `ms`
- Création de `lib/util/jobs`
- Ajout des jobs au worker
- Lancement de harvest depuis la route `/admin/start-harvest`

2022-10-14 09:01 UTC, tmerlier requested changes

2022-10-14 09:35 UTC, GllmR approved these changes

2022-10-16 20:31 UTC, jdesboeufs approved these changes

2022-10-16 20:37 UTC, jdesboeufs commented
@cedric-famibelle-pronzola j'ai pas mal restructuré les choses, essentiellement pour que ce soit limpide après notre départ de ce projet.

Je te laisse jeter un oeil demain matin mais on va rapidement passer à la suite.
Je prends tes questions en privé.

2022-10-17 21:34 UTC, merged