Nouvelles routes et possibilité d'éditer une source
BaseAdresseNationale/moissonneur-bal pull request #28
Opened 2022-10-20 14:48 UTC by cedric-famibelle-pronzola

- Nouvelles routes :
  - GET `/sources/:sourceId/harvests` retourne les 10 derniers moissonnages d'une source
  - GET `/harvest/:harvestId` retourne un moissonnage en fonction de son id
  - PUT `/sources/:sourceId` permet l'édition d'une source ⬇️
```
{
    enabled: bool,
    perimetre: array
}
```
 
- Création de `harvestEnabled` et ajout dans la liste des jobs. Retourne les sources "actives" `{enabled: true}`

2022-10-21 08:01 UTC, tmerlier approved these changes

2022-10-21 15:27 UTC, GllmR approved these changes

2022-10-24 10:14 UTC, jdesboeufs requested changes

2022-10-24 10:14 UTC, jdesboeufs commented on lib/models/source.js
> +    {_id: {$nin: activeIds}, enabled: true, _deleted: false},
Non tu ne dois pas toucher à ce champ `enabled`, il faut qu'en cas de retour de la source elle retrouve son état initial.

2022-10-24 10:14 UTC, jdesboeufs commented on lib/models/source.js
> +      enabled: true,
On laisse finir quand même.

2022-10-24 10:14 UTC, jdesboeufs commented on lib/sources/index.js
> +    enabled: true,
Non je mettrai plutôt ça dans l'upsert.

2022-10-24 10:14 UTC, jdesboeufs commented on lib/models/source.js
> +    if (!Array.isArray(perimetre)) {
Voir avec @tmerlier mais on peut mieux tester, vérifier qu'on a des strings et qui ont la tête attendue.
Pas urgent cela-dit.

2022-10-24 10:14 UTC, jdesboeufs commented on lib/models/source.js
> +
On vérifie qu'il y a des trucs dans sourceChanges. `Object.keys(sourceChanges).length > 0`

2022-10-24 10:14 UTC, jdesboeufs commented on lib/models/source.js
> +async function getEnabledSources() {
Le libellé de la fonction correspond pas vraiment à ce que ça fait.
Là on retourne les sources actives qui sont pas en cours de moissonnage.

Par ailleurs cette fonction ne semble pas utilisée.

2022-10-26 06:37 UTC, jdesboeufs requested changes

2022-10-26 06:37 UTC, jdesboeufs commented on lib/models/source.js
> +      enabled: true,
Il faut enlever ce critère sinon un moissonnage en cours dont la source est désactivée au même moment reste bloqué dans ls limbes.

2022-10-26 06:39 UTC, jdesboeufs approved these changes

2022-10-26 06:39 UTC, merged