Correction du message d'erreur lors du rejet d'un fichier
BaseAdresseNationale/moissonneur-bal pull request #37
Opened 2022-11-09 10:49 UTC by cedric-famibelle-pronzola

À l'heure actuelle, le message d'erreur n'est pas retourné correctement quand un fichier est rejeté à cause du "parsing".
- Ajout de la fonction `getErrorCodes` dans `lib/util/validate-file`

2022-11-09 11:26 UTC, jdesboeufs commented on lib/harvest/handle-new-file.js
> +      updateRejectionReason: `Unable to parse CSV file: ${getErrorCodes(result.parseErrors)}`,
Je te suggère de laisser le formatage ici et que `getErrorCodes` retourne un tableau.
Par contre donne un dommage plus explicite car c'est uniquement applicable aux erreurs de parsing.
Je suggère : `getParsingErrorCodes(result) => ['TooManyTruc', 'TooFewTruc']`

2022-11-10 09:08 UTC, jdesboeufs requested changes

2022-11-10 09:08 UTC, jdesboeufs commented on lib/util/validate-file.js
> +  return uniq(errorCodes)
T'as pas besoin du `uniq` si tu utilises `[..newSet()]` qui fait exactement ça.
Choisis l'un ou l'autre :)

2022-11-10 09:09 UTC, cedric-famibelle-pronzola commented on lib/util/validate-file.js
> +  return uniq(errorCodes)
effectivement 🙃

2022-11-10 09:16 UTC, jdesboeufs approved these changes

2022-11-10 09:16 UTC, merged