Feat: add organization and perimeter
BaseAdresseNationale/moissonneur-bal pull request #88
Opened 2024-02-13 08:48 UTC by fufeck

2024-02-16 13:10 UTC, MaGOs92 requested changes

2024-02-16 13:10 UTC, MaGOs92 commented on lib/models/organization.js
> +  if (updateResult.matchedCount <= 0) {
Pourquoi ne pas utiliser le flag upsert comme dans la fonction d'après? Y'a pas moyen de fusionner ces deux fonctions pour gérer le périmètre?

2024-02-16 13:10 UTC, MaGOs92 commented on lib/util/perimeters.js
> +const {getCommuneByDepartement, getEPCI} = require('./cog.js')
à discuter ensemble mais je trouve que c'est un peu dommage d'avoir ce code dupliqué ici et dans l'API dépot. ça n'aurait pas été possible de le mettre dans le validateur BAL avec un flag genre "validate(bal, {format: "1.3", perimeter})"

2024-02-16 13:33 UTC, MaGOs92 commented
Tests : J'ai testé avec Amiens, ça fonctionne bien. Par contre j'ai l'impression que ça va être un gros taff de mettre les périmètres dans toutes les orgas

2024-02-19 10:19 UTC, fufeck commented on lib/harvest/handle-new-file.js
> +  return row.parsedValues.commune_insee || row.additionalValues.cle_interop?.codeCommune
Yes, c'était une vielle fonction que j'ai pas pensé a supprimer ;)

2024-02-19 10:59 UTC, fufeck commented on lib/util/perimeters.js
> +const {getCommuneByDepartement, getEPCI} = require('./cog.js')
D'après moi, le validateur est simplement pour vérifié que le fichier BAL respecte bien le format. Il n'est pas fonctionnel, c'est a dire qu'il ne vérifie pas que les données soient logiques (un peu comme l'erreur commune_insee.valeur_inattendue quand il y a plusieurs commune insee dans le même fichier BAL, ce n'est pas interdit pas le format mais par l'api-depot). Pour moi l'erreur du périmètre ne vient pas du format BAL.
Ensuite comme pour le fichier cog.js qui est présent a plusieurs endroit du code (et qui a les même fonctions), je pense que la bonne pratique serait de faire un package pour les briques partagé mais celle ci sont trop petites et trop compliqué a maintenir via des packages.
Je pense donc que la solution choisit par Theo de garder des duplicas de petites fonctions entre les projets est le plus simple et efficace.

2024-02-20 16:35 UTC, MaGOs92 approved these changes
LGTM, Après la migration j'ai relancé manuellement quelques moissonnages et tout est passé

2024-02-20 16:35 UTC, MaGOs92 commented on migrations/2024-02-20-generate-organizations.js
> +    console.log(orga._id)
à supprimer

2024-02-26 09:39 UTC, merged